parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: atsnet2
    database_user: atsnet2
    database_password: flolaweb112
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 4c1af36e193bf7243f3460643ff4931039847b9c
    database_path: null
