security:
    encoders:
        Atemschutz\CoreBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_CORE_MANAGER: [ROLE_USER]
        ROLE_CORE_ADMIN: [ROLE_CORE_MANAGER, ROLE_USER]
        ROLE_CORE_SADMIN: [ROLE_CORE_ADMIN, ROLE_CORE_MANAGER, ROLE_USER]
        ROLE_NACHWEIS_VIEWER: [ROLE_USER]
        ROLE_NACHWEIS_MANAGER: [ROLE_NACHWEIS_VIEWER, ROLE_USER]
        ROLE_NACHWEIS_ADMIN: [ROLE_NACHWEIS_MANAGER, ROLE_NACHWEIS_VIEWER, ROLE_USER]

    providers:
        main:
            entity: { class: 'Atemschutz\CoreBundle\Entity\User' }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        secured_area:
            remember_me:
                key: "%secret%"
                lifetime: 7200 # 2 hours in seconds
                path: /
                domain: ~
            pattern: ^/
            anonymous: ~
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/css, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/js, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/images, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/core/account, roles: ROLE_USER }
        - { path: ^/core/user, roles: ROLE_CORE_MANAGER }
        - { path: ^/core/user/delete, roles: ROLE_CORE_ADMIN }
        - { path: ^/core/standort, roles: ROLE_CORE_ADMIN }
        
        - { path: ^/nachweis/atemschutzgeraetetraeger/showMy, roles: ROLE_USER }
        - { path: ^/nachweis/atemschutzgeraetetraeger, roles: ROLE_NACHWEIS_VIEWER }
        - { path: ^/nachweis/atemschutzgeraetetraeger/index, roles: ROLE_NACHWEIS_MANAGER }
        - { path: ^/nachweis/atemschutzgeraetetraeger/new, roles: ROLE_NACHWEIS_MANAGER }
        - { path: ^/nachweis/atemschutzgeraetetraeger/edit, roles: ROLE_NACHWEIS_MANAGER }
        - { path: ^/nachweis/atemschutzgeraetetraeger/delete, roles: ROLE_NACHWEIS_ADMIN }
        - { path: ^/nachweis/einsatzart, roles: ROLE_NACHWEIS_ADMIN }
        - { path: ^/nachweis/g26, roles: ROLE_NACHWEIS_MANAGER }
        - { path: ^/nachweis/g26/delete, roles: ROLE_NACHWEIS_ADMIN }
        - { path: ^/nachweis/nachweisart, roles: ROLE_NACHWEIS_ADMIN }
        - { path: ^/nachweis/nachweis/show, roles: ROLE_USER }
        - { path: ^/nachweis/nachweis, roles: ROLE_NACHWEIS_MANAGER }
        - { path: ^/nachweis/nachweis/delete, roles: ROLE_NACHWEIS_ADMIN }
        
        - { path: ^/, roles: ROLE_USER }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
