<?php

namespace Proxies\__CG__\Atemschutz\NachweisBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class G26 extends \Atemschutz\NachweisBundle\Entity\G26 implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setDuedate($duedate)
    {
        $this->__load();
        return parent::setDuedate($duedate);
    }

    public function getDuedate()
    {
        $this->__load();
        return parent::getDuedate();
    }

    public function setClassification($classification)
    {
        $this->__load();
        return parent::setClassification($classification);
    }

    public function getClassification()
    {
        $this->__load();
        return parent::getClassification();
    }

    public function setAtemschutzgeraetetraeger(\Atemschutz\NachweisBundle\Entity\Atemschutzgeraetetraeger $atemschutzgeraetetraeger = NULL)
    {
        $this->__load();
        return parent::setAtemschutzgeraetetraeger($atemschutzgeraetetraeger);
    }

    public function getAtemschutzgeraetetraeger()
    {
        $this->__load();
        return parent::getAtemschutzgeraetetraeger();
    }

    public function setValid($valid)
    {
        $this->__load();
        return parent::setValid($valid);
    }

    public function getValid()
    {
        $this->__load();
        return parent::getValid();
    }

    public function setAtemschutzgeraetewart(\Atemschutz\CoreBundle\Entity\User $atemschutzgeraetewart = NULL)
    {
        $this->__load();
        return parent::setAtemschutzgeraetewart($atemschutzgeraetewart);
    }

    public function getAtemschutzgeraetewart()
    {
        $this->__load();
        return parent::getAtemschutzgeraetewart();
    }

    public function setNotice($notice)
    {
        $this->__load();
        return parent::setNotice($notice);
    }

    public function getNotice()
    {
        $this->__load();
        return parent::getNotice();
    }

    public function getDateFormatted($format = 'd.m.Y')
    {
        $this->__load();
        return parent::getDateFormatted($format);
    }

    public function getDueDateFormatted($format = 'd.m.Y')
    {
        $this->__load();
        return parent::getDueDateFormatted($format);
    }

    public function isInvalid()
    {
        $this->__load();
        return parent::isInvalid();
    }

    public function expiresInLessThanOneMonth()
    {
        $this->__load();
        return parent::expiresInLessThanOneMonth();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'date', 'duedate', 'valid', 'classification', 'notice', 'atemschutzgeraetetraeger', 'atemschutzgeraetewart');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}